[tools]
bun = "1.3.0"
dprint = "latest"
lefthook = "latest"
"npm:turbo" = "latest"

[settings]
npm.bun = true

[tasks.update-vrt-screenshots]
description = "Update VRT screenshots"
run = [
  "docker compose up -d --remove-orphans",
  "docker compose exec linux-vrt sh -c 'cd apps/roppoh && bun run test:visual --update'",
  "docker compose exec linux-vrt sh -c 'cd apps/ura-roppoh && bun run test:visual --update'",
  "docker compose down --remove-orphans",
  "bun run --cwd apps/roppoh test:visual --update",
  "bun run --cwd apps/ura-roppoh test:visual --update",
]
