name: ci
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-bun-turbo
      - uses: dprint/check@v2.3
      - run: bun biome ci
      - run: bun turbo check:type
      - run: bun run knip
      - run: bun turbo build

  playwright-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: lint-and-build
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-buildx-action@v3
      - name: Run vrt docker container
        run: docker compose up -d
      - name: "roppoh vrt"
        run: docker compose exec linux-vrt sh -c "bun run --cwd apps/roppoh test:visual"
      - name: "ura-roppoh vtr"
        run: docker compose exec linux-vrt sh -c "bun run --cwd apps/ura-roppoh test:visual"
      - run: docker compose down
      - name: Upload VRT screenshots
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: vrt-diff-screenshots
          path: |
            apps/roppoh/.vitest-attachments/**/*.png
            apps/roppoh/test/visual-regression/**/__screenshots__/**/*.png
            apps/ura-roppoh/.vitest-attachments/**/*.png
            apps/ura-roppoh/test/visual-regression/**/__screenshots__/**/*.png
          retention-days: 7

  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: lint-and-build
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-bun-turbo
      - run: bun run test:unit
        working-directory: apps/roppoh
      - run: bun run test
        working-directory: apps/fujimatsu
